version: '3.7'
services:
  web:
    restart: on-failure
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile_web
    command:  uvicorn main:app --reload --port 8002 --host 0.0.0.0

    ports:
      - 8002:8002

    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: on-failure
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=daniil
      - POSTGRES_PASSWORD=daniil1234
      - POSTGRES_DB=detected_objects
volumes:
  postgres_data: