FROM python:3.11-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip \
    && apt-get update; \
    apt-get install -y \
    libpq-dev \
    gcc \
    musl-dev \
    g++;

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .